
GET http://localhost:3000/api/countries
Content-Type: application/json


######


GET http://localhost:3000/api/routes/?origen=BCN&destino=CGN
Content-Type: application/json



######


GET http://localhost:3000/api/routes/?bcn&mad
Content-Type: application/json


#######



GET http://localhost:3000/api/airlines
Content-Type: application/json


######


GET http://localhost:3000/api/airports
Content-Type: application/json


######


GET http://localhost:3000/api/cities
Content-Type: application/json


######




GET http://localhost:3000/api/routes/?BCN&jaj
Content-Type: application/json



###########


POST http://localhost:3000/api/users/register/
Content-Type: application/json

{
    "userId":9,
    "username":"us",
    "password":"pasword1",
    "rol":"user",
    "routes":[]
}